# -*- coding: utf-8 -*-
"""
Created on Sun Feb  9 20:20:15 2025

@author: hp
"""

import sys
import numpy as np
import operator
import os


file_name = sys.argv[1]
n = int(sys.argv[2])
n_change = int(sys.argv[3])

if not len(sys.argv) == 4:
    print("Command usage: python angle_type_changer.py file_name n n_change")
    print("where     file_name    is a file, name of the initial condition file")
    print("          n            is an integer, the number of beads in the polymer ")
    print("          nchange      is an integer, the number of angle types to be changed")

# Using n and knowledge of the standard
# initial conditions file generated by the code
# we can calculate the index of the start of the
# angles section
angle_n = 16 + 6 + n + 3 + n + 3 + n + 3 + n + 3
# Note: this is the index for the first line of
# angle data

atom_file = open(file_name, "r")
lines = atom_file.readlines()
atom_file.close()

lines[9] = " 3 angle types\n"

for i in range(1, 2*n_change + 1, 2):
    index = angle_n + i
    which_angle = i + 1
    base_atom = int(which_angle/2)
    lines[index] = f" {i+1} 3 {base_atom} {base_atom+1} {base_atom+2}\n"

    
update = open(file_name, "w")
update.writelines(lines)
update.close()

print(f"{n_change} angles changed from type 1 to 3")
