# -*- coding: utf-8 -*-
"""
Created on Sun Feb  9 20:20:15 2025

@author: hp
"""

import sys
import numpy as np
import operator
import os


file_name = sys.argv[1]
n = int(sys.argv[2])
n_change = int(sys.argv[3])
# Using n and knowledge of the standard
# initial conditions file generated by the code
# we can calculate the index of the start of the
# angles section
angle_n = 16 + 6 + n + 3 + n + 3 + n + 3 + n + 2
# Note: this is the index for the line before the 
# angle types; the loop goes from 1, and goes in 
# multiples of 2, so this hits the first 150 
# polytorsion angles

atom_file = open(file_name, "r")
lines = atom_file.readlines()
atom_file.close()

lines[9] = " 3 angle types\n"

for i in range(1, 2*n_change + 1, 2):
    index = angle_n + i
    which_angle = i
    base_atom = int((which_angle+1)/2)
    lines[index] = f" {i} 3 {base_atom} {base_atom+1} {base_atom+2}\n"

    
update = open(file_name, "w")
update.writelines(lines)
update.close()

print(f"{n_change} angles changed from type 1 to 3")
